classdef TestTomlRead < matlab.unittest.TestCase

  methods (Test)

    function testReadExample(testCase)
      matl_strct = struct( ...
          'title', 'TOML Example' ...
        , 'owner', struct( ...
            'name', 'Tom Preston-Werner' ...
          , 'dob', '1979-05-27T07:32:00-08:00' ...
            ) ...
        , 'database', struct( ...
            'server', '192.168.1.1' ...
          , 'ports', int64([8001, 8001, 8002]) ...
          , 'connection_max', int64(5000) ...
          , 'enabled', true ...
            ) ...
        , 'servers', struct( ...
            'alpha', struct( ...
                'ip', '10.0.0.1' ...
              , 'dc', 'eqdc10' ...
                ) ...
          , 'beta', struct( ...
              'ip', '10.0.0.2' ...
            , 'dc', 'eqdc10' ...
              ) ...
            ) ...
        , 'clients', struct( ...
            'data', {{{'gamma', 'delta'}, int64([1, 2])}} ...
          , 'hosts', {{'alpha', 'omega'}} ...
            ) ...
          );

      c_dir = fileparts(fileparts(mfilename('fullpath')));
      example_file = fullfile(c_dir, 'example.toml');

      testCase.verifyEqual(toml.read(example_file), matl_strct, ...
                           'Did not parse example TOML file correctly.')
    end

  end

end