classdef TestTomlEncode < matlab.unittest.TestCase

  methods (Test)

    function testValidation(testCase)
      matl_obj = { ...
          1 ...
        , {'a', 'b', 'c'} ...
        , struct('abc', {'a', 'b', 'c'}) ...
                 };
      err_type = { ...
          'toml:InvalidBaseType' ...
        , 'toml:InvalidBaseType' ...
        , 'toml:NonScalarStruct' ...
                 };

      err_msg = { ...
          'Did not reject a non-struct base type.' ...
        , 'Did not reject a non-struct base type.' ...
        , 'Did not reject a multidimensional base table.' ...
                };

      for indx = 1:numel(matl_obj)
        testCase.verifyError(@() toml.encode(matl_obj{indx}), ...
                             err_type{indx}, err_msg{indx})
      end
    end

    function testRoundTrip(testCase)
      test_strct = struct( ...
          'field1', 'abcdefg' ...
        , 'field2', [1, 2, 3] ...
        , 'field3', {{'a', 'b', 'c'}} ...
        , 'field4', struct('sub1field1', 'wxyz') ...
        , 'field5', struct('sub2field1', struct('subsub1field1', 'lmnop')) ...
          );

      testCase.verifyEqual(toml.decode(toml.encode(test_strct)), test_strct, ...
        'Did not perform a round-trip serialize/deserialize correctly.')
    end

  end

end