name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: matlab-actions/setup-matlab@v1
    - uses: matlab-actions/run-tests@v1
    - uses: g-s-k/toml-test-action@v1.0.2
      with:
        command: ./ci.bash /home/runner/work/_actions/matlab-actions/run-tests/v1/dist/bin/glnxa64/run-matlab-command
